# Generated by Django 5.0.6 on 2026-07-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_format',
            field=models.CharField(blank=True, default='MM/DD/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(blank=True, default='GMT+0', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
