# Generated by Django 6.0.6 on 2026-07-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_date_format_company_support_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('employee', 'Employee'), ('superadmin', 'Super Admin')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('employee', 'Employee'), ('superadmin', 'Super Admin')], default='employee', max_length=20),
        ),
    ]
