# Generated by Django 5.0.6 on 2026-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketcomment_ticketactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comment_files/'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
