import { useState, useEffect } from "react";
import { FiDownload, FiPrinter, FiBriefcase, FiUsers, FiClipboard, FiBox, FiClock } from "react-icons/fi";
import api from "../../services/api";
import "../settings/Settings.css";

const ACTIVITY_LOG_KEY = "td_report_activity_log";

function loadActivityLog() {
  try {
    const raw = localStorage.getItem(ACTIVITY_LOG_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

function toCSV(rows) {
  if (!rows.length) return "";
  const headers = Object.keys(rows[0]);
  const escape = (v) => `"${String(v).replace(/"/g, '""')}"`;
  const lines = [headers.join(","), ...rows.map((r) => headers.map((h) => escape(r[h])).join(","))];
  return lines.join("\n");
}

function formatTimestamp(date) {
  return date.toLocaleString("en-GB", {
    day: "2-digit", month: "short", year: "numeric", hour: "numeric", minute: "2-digit", hour12: true,
  }).replace(",", "").replace(/am|pm/i, (m) => m.toUpperCase());
}

function buildHeaderLines(report, generatedBy) {
  const now = formatTimestamp(new Date());
  return [
    "TickDesk",
    `${report.title} Report`,
    "",
    `Generated By : ${generatedBy}`,
    `Generated On : ${now}`,
    `Total ${report.title} : ${report.rows.length}`,
    "",
  ];
}

function downloadCSV(report, generatedBy) {
  const headerLines = buildHeaderLines(report, generatedBy).map((l) => `"${l}"`).join("\n");
  const csv = `${headerLines}\n${toCSV(report.rows)}`;
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = report.filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function printReport(report, generatedBy) {
  const headerLines = buildHeaderLines(report, generatedBy);
  const headers = Object.keys(report.rows[0] || {});
  const win = window.open("", "_blank", "width=900,height=700");
  win.document.write(`
    <html>
      <head>
        <title>${report.title} Report — TickDesk</title>
        <style>
          body { font-family: -apple-system, "Segoe UI", Arial, sans-serif; padding: 32px; color: #111827; }
          h1 { font-size: 20px; margin: 0 0 2px; }
          h2 { font-size: 14px; font-weight: 600; color: #374151; margin: 0 0 16px; }
          .meta { font-size: 12px; color: #6b7280; margin: 2px 0; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #e5e7eb; font-size: 12px; }
          th { text-transform: uppercase; letter-spacing: 0.04em; color: #6b7280; font-size: 10px; }
        </style>
      </head>
      <body>
        <h1>${headerLines[0]}</h1>
        <h2>${headerLines[1]}</h2>
        <p class="meta">${headerLines[3]}</p>
        <p class="meta">${headerLines[4]}</p>
        <p class="meta">${headerLines[5]}</p>
        <table>
          <thead><tr>${headers.map((h) => `<th>${h}</th>`).join("")}</tr></thead>
          <tbody>
            ${report.rows.map((r) => `<tr>${headers.map((h) => `<td>${r[h]}</td>`).join("")}</tr>`).join("")}
          </tbody>
        </table>
      </body>
    </html>
  `);
  win.document.close();
  win.focus();
  win.print();
}

const REPORT_META = [
  { key: "companies", Icon: FiBriefcase, color: "#2563eb", title: "Companies", desc: "Every registered company, its admin, and headline counts.",       filename: "tickdesk-companies.csv" },
  { key: "users",     Icon: FiUsers,     color: "#16a34a", title: "Users",     desc: "Every user across every company, with role and department.",     filename: "tickdesk-users.csv" },
  { key: "tickets",   Icon: FiClipboard, color: "#7c3aed", title: "Tickets",   desc: "Every ticket across every company, with requester and assignee.", filename: "tickdesk-tickets.csv" },
  { key: "assets",    Icon: FiBox,       color: "#ea580c", title: "Assets",    desc: "Every asset across every company, with owner and purchase date.", filename: "tickdesk-assets.csv" },
];

export default function Reports() {
  const [downloaded, setDownloaded] = useState(null);
  const [generatedBy, setGeneratedBy] = useState("—");
  const [activityLog, setActivityLog] = useState(loadActivityLog);
  const [reportRows, setReportRows] = useState({ companies: [], users: [], tickets: [], assets: [] });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get("accounts/profile/")
      .then((r) => {
        const name = `${r.data.first_name || ""} ${r.data.last_name || ""}`.trim() || r.data.username;
        setGeneratedBy(name);
      })
      .catch(() => {});

    Promise.all([
      api.get("platform/reports/companies/"),
      api.get("platform/reports/users/"),
      api.get("platform/reports/tickets/"),
      api.get("platform/reports/assets/"),
    ])
      .then(([companies, users, tickets, assets]) => {
        setReportRows({ companies: companies.data, users: users.data, tickets: tickets.data, assets: assets.data });
      })
      .finally(() => setLoading(false));
  }, []);

  const REPORTS = REPORT_META.map((m) => ({ ...m, rows: reportRows[m.key] }));

  const logActivity = (report, action, by) => {
    const entry = { id: Date.now(), report: report.title, action, by, at: formatTimestamp(new Date()) };
    setActivityLog((log) => {
      const next = [entry, ...log].slice(0, 20);
      localStorage.setItem(ACTIVITY_LOG_KEY, JSON.stringify(next));
      return next;
    });
  };

  const clearActivityLog = () => {
    setActivityLog([]);
    localStorage.removeItem(ACTIVITY_LOG_KEY);
  };

  const handleExport = (report) => {
    downloadCSV(report, generatedBy);
    logActivity(report, "CSV Export", generatedBy);
    setDownloaded(report.title);
    setTimeout(() => setDownloaded(null), 3000);
  };

  const handlePrint = (report) => {
    printReport(report, generatedBy);
    logActivity(report, "Print", generatedBy);
  };

  return (
    <div className="st-page" style={{ gridTemplateColumns: "1fr" }}>
      <div className="st-main">
        <div>
          <h1 className="st-page-title">Reports</h1>
          <p className="st-page-sub">Export platform-wide data as CSV, or print a formatted copy.</p>
        </div>

        {downloaded && (
          <div style={{ background: "#f0fdf4", border: "1.5px solid #bbf7d0", color: "#16a34a", fontSize: 13, fontWeight: 600, padding: "10px 16px", borderRadius: 10 }}>
            {downloaded}.csv downloaded.
          </div>
        )}

        <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12 }}>
          {REPORTS.map((r) => (
            <div key={r.key} className="st-card">
              <div className="st-card-body">
                <div style={{
                  width: 40, height: 40, borderRadius: 10, background: `${r.color}1a`, color: r.color,
                  display: "flex", alignItems: "center", justifyContent: "center", marginBottom: 14,
                }}>
                  <r.Icon size={18} />
                </div>
                <p style={{ fontSize: 15, fontWeight: 700, color: "#111827", margin: "0 0 6px" }}>{r.title}</p>
                <p style={{ fontSize: 12, color: "#6b7280", margin: "0 0 16px", lineHeight: 1.5 }}>{r.desc}</p>
                <p style={{ fontSize: 11, color: "#9ca3af", margin: "0 0 12px" }}>{loading ? "Loading…" : `${r.rows.length} records`}</p>
                <div style={{ display: "flex", gap: 8 }}>
                  <button className="st-btn-secondary" style={{ flex: 1, justifyContent: "center" }} disabled={loading || !r.rows.length} onClick={() => handleExport(r)}>
                    <FiDownload size={14} /> CSV
                  </button>
                  <button className="st-btn-secondary" style={{ flex: 1, justifyContent: "center" }} disabled={loading || !r.rows.length} onClick={() => handlePrint(r)}>
                    <FiPrinter size={14} /> Print
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Activity log — what's been exported/printed, by whom, and when */}
        <div className="st-card">
          <div className="st-card-header">
            <h2 className="st-card-title"><FiClock size={15} color="#2563eb" /> Activity Log</h2>
            {activityLog.length > 0 && (
              <button
                onClick={clearActivityLog}
                style={{ background: "none", border: "none", padding: 0, fontSize: 12, fontWeight: 600, color: "#9ca3af", cursor: "pointer" }}
              >
                Clear
              </button>
            )}
          </div>
          {activityLog.length === 0 ? (
            <div className="st-card-body">
              <p style={{ fontSize: 13, color: "#9ca3af", margin: 0 }}>No exports or prints yet — actions taken above will show up here.</p>
            </div>
          ) : (
            <div className="st-table-wrap">
              <table className="st-table">
                <thead>
                  <tr><th>REPORT</th><th>ACTION</th><th>GENERATED BY</th><th>WHEN</th></tr>
                </thead>
                <tbody>
                  {activityLog.map((entry) => (
                    <tr key={entry.id}>
                      <td style={{ fontWeight: 600, color: "#111827" }}>{entry.report}</td>
                      <td>
                        <span className={`st-badge ${entry.action === "Print" ? "st-badge-blue" : "st-badge-green"}`}>{entry.action}</span>
                      </td>
                      <td style={{ color: "#6b7280" }}>{entry.by}</td>
                      <td style={{ color: "#6b7280" }}>{entry.at}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
