import { useState } from "react";
import { FiKey, FiMoreVertical, FiPlus, FiShield, FiAlertTriangle } from "react-icons/fi";
import "../settings/Settings.css";

const apiKeys = [
  { name: "Production Webhook", status: "Active",  statusCls: "st-badge-green", created: "Oct 12, 2023" },
  { name: "Staging Integration", status: "Active",  statusCls: "st-badge-green", created: "Nov 04, 2023" },
  { name: "Legacy Reporter",     status: "Expired", statusCls: "st-badge-red",   created: "Jan 15, 2023" },
];

const securityActivity = [
  { text: "API Key Created",        meta: "New key 'Production Webhook' generated by Admin.\n2 hours ago",      dot: "#6b7280" },
  { text: "Policy Updated",         meta: "Password complexity requirements increased.\n6 hours ago",            dot: "#6b7280" },
  { text: "Failed Login Attempt",   meta: "IP 192.168.1.1 tried to access from London.\nYesterday",             dot: "#dc2626" },
];

export default function Security() {
  const [tfa, setTfa] = useState(true);

  return (
    <div className="st-page">
      <div className="st-main">
        <div>
          <h1 className="st-page-title">Security Settings</h1>
          <p className="st-page-sub">Manage enterprise-grade authentication and access policies for your organization.</p>
        </div>

        {/* Core Security Policies */}
        <div className="st-card">
          <div className="st-card-header">
            <h2 className="st-card-title"><FiShield size={16} color="#2563eb" /> Core Security Policies</h2>
          </div>
          <div className="st-card-body">
            {/* 2FA Toggle */}
            <div className="st-toggle-wrap">
              <div className="st-toggle-info">
                <p className="st-toggle-label">Two-Factor Authentication (2FA)</p>
                <p className="st-toggle-desc">Require all administrators to use an authentication app to sign in.</p>
              </div>
              <label className="st-toggle">
                <input type="checkbox" checked={tfa} onChange={() => setTfa(!tfa)} />
                <span className="st-toggle-slider" />
              </label>
            </div>

            <div className="st-form-grid" style={{ marginTop: 16 }}>
              <div className="st-field">
                <label>Password Policy</label>
                <div className="st-select-wrap">
                  <select className="st-select">
                    <option>Min 8 characters</option>
                    <option>Min 12 characters</option>
                    <option>Complex (upper, lower, symbol)</option>
                  </select>
                </div>
              </div>
              <div className="st-field">
                <label>Session Timeout</label>
                <div className="st-select-wrap">
                  <select className="st-select">
                    <option>30 minutes</option>
                    <option>1 hour</option>
                    <option>4 hours</option>
                  </select>
                </div>
              </div>
            </div>

            <div style={{ display: "flex", justifyContent: "flex-end", marginTop: 16 }}>
              <button className="st-btn-primary">Save Changes</button>
            </div>
          </div>
        </div>

        {/* API Keys */}
        <div className="st-card">
          <div className="st-card-header">
            <h2 className="st-card-title"><FiKey size={16} color="#2563eb" /> API Keys</h2>
            <button className="st-btn-secondary st-btn-sm"><FiPlus size={13} /> Create API Key</button>
          </div>
          <div className="st-table-wrap">
            <table className="st-table">
              <thead>
                <tr>
                  <th>KEY NAME</th>
                  <th>STATUS</th>
                  <th>CREATED DATE</th>
                  <th>ACTIONS</th>
                </tr>
              </thead>
              <tbody>
                {apiKeys.map((k) => (
                  <tr key={k.name}>
                    <td style={{ fontWeight: 500, color: "#111827" }}>{k.name}</td>
                    <td><span className={`st-badge ${k.statusCls}`}>{k.status}</span></td>
                    <td style={{ color: "#6b7280" }}>{k.created}</td>
                    <td><button className="st-icon-btn"><FiMoreVertical size={14} /></button></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Right panel */}
      <div className="st-right">
        {/* System Health dark */}
        <div className="st-panel-dark">
          <p className="st-panel-title">System Health</p>
          {[
            { label: "Identity Service", val: "Operational", color: "#34d399" },
            { label: "Auth Proxy",       val: "Operational", color: "#34d399" },
          ].map((s) => (
            <div key={s.label} className="st-dark-status-row">
              <span className="st-dark-label">{s.label}</span>
              <span className="st-dark-value" style={{ color: s.color }}>● {s.val}</span>
            </div>
          ))}
          <div className="st-dark-bar-bg"><div className="st-dark-bar" style={{ width: "99.9%" }} /></div>
          <p className="st-dark-uptime">99.9% UPTIME LAST 30 DAYS</p>
        </div>

        {/* Security Activity */}
        <div className="st-panel-card">
          <p className="st-panel-title">Security Activity</p>
          <ul className="st-timeline">
            {securityActivity.map((a) => (
              <li key={a.text} className="st-timeline-item">
                <span className="st-timeline-dot" style={{ background: a.dot, borderColor: a.dot + "33" }} />
                <div className="st-timeline-text">
                  <p>{a.text}</p>
                  {a.meta.split("\n").map((m, i) => <span key={i} style={{ display: "block" }}>{m}</span>)}
                </div>
              </li>
            ))}
          </ul>
          <button style={{ fontSize: 12, color: "#2563eb", fontWeight: 600, background: "none", border: "none", cursor: "pointer", marginTop: 10 }}>
            View Audit Logs
          </button>
        </div>

        {/* Security tip */}
        <div className="st-tip-card">
          <div style={{ fontSize: 18 }}>💡</div>
          <div className="st-tip-text">
            <p><strong>Security Tip</strong></p>
            <p>Enabling Hardware Security Keys can reduce phishing risks by up to 99% compared to traditional 2FA apps.</p>
            <a href="#">Learn more</a>
          </div>
        </div>
      </div>
    </div>
  );
}
